### ISSUE TITLE
New footnote style TO-DO list

### ISSUE THREAD

**Issue by Devices** [redtexts/texts#3]
I have compiled a list of texts that do not have the "correct" footnote style yet. Some are more work than others. I have already "fixed" some texts with 1-3 footnotes.

This would be perfect for new contributors to do if they want to do something simple, yet meaningful addition. Sadly it would be invisible to most people, but we will thank you. Of course I, and probably the other maintainers, will (slowly) work on this as well. It is, of course, possible that I have missed one or two texts with "wrong" footnotes, so keep an eye open.

- [ ] _Trapped at a Party Where No One Likes You_ By Surplus Club (2015)
- [ ] _Marx versus Historical Materialism_ By Smith, Cyril (1999)
- [ ] _Marxism in a Nutshell: From the Criticism of Capitalism to a Classless Society_ By Robin Goodfellow (2013)
- [ ] _Marx-Engels and Democracy (Part One)_ By Robin Goodfellow (2002)
- [ ] _World Revolution and Communist Tactics_ By Pannekoek, Anton (1920)
- [ ] _The German Ideology, Part I_ By Marx, Karl; Engels, Friedrich (1845)
- [ ] _The Question of the State_ By La Guerre Sociale (1978)
- [ ] _Why Wealth Redistribution Cannot Solve Capitalism’s Crisis_ By Internationalist Perspective (2014)
- [ ] _Trotsky and Trotskyism_ By Internationalist Communist Tendency (2000)
- [ ] _The Perspective of Communism_ By International Communist Current (2004)
- [ ] _The World Revolution_ By Gorter, Herman (1923)
- [ ] _The Communist Workers’ International_ By Gorter, Herman (1923)
- [ ] _The Organisation of the Proletariat’s Class Struggle_ By Gorter, Herman (1921)
- [ ] _Open Letter to Comrade Lenin_ By Gorter, Herman (1920)
- [ ] _The World Revolution_ By Gorter, Herman (1918)
- [ ] _Communism is the Material Human Community: Amadeo Bordiga Today_ By Goldner, Loren (1991)
- [ ] _The Evolution of Capitalism and the New Perspective_ By Gauche Communiste de France (1952)
- [ ] _Present Problems of the Workers’ Movement: "Discipline, the Principle Strength"_ By Gauche Communiste de France (1947)
- [ ] _Nature and Function of the Proletarian Party_ By Gauche Communiste de France (1947)
- [ ] _The Task of the Hour: Formation of the Party or Formation of Cadres_ By Gauche Communiste de France (1946)
- [ ] _Communisation and Value-Form Theory_ By Endnotes (2010)
- [ ] _A User’s Guide to Détournement_ By Debord, Guy; Wolman, Gil J. (1956)
- [ ] _When Insurrections Die_ By Dauvé, Gilles (1979)
- [ ] _Capitalism and Communism_ By Dauvé, Gilles (1972)
- [ ] _Bordigism_ By Buick, Adam (1987)
- [ ] _Bordiga versus Pannekoek_ By Antagonism (2000-2001)
- [ ] _Give Up Activism_ By Anonymous (1999)
